# Example KiPlot config file
kibot:
  version: 1

preflight:
  run_erc: true
  erc_warnings: true
  update_xml: true
  run_drc: true
  check_zone_fills: true
  ignore_unconnected: false

outputs:
  - name: 'print_sch'
    comment: "Print schematic (PDF)"
    type: pdf_sch_print
    dir: .
    options:
      output: '%f.pdf'
